language: python

python:
  - 3.6

services:
  - docker
env:
  - CODECOV_TOKEN='37b15870-5f46-4979-a623-066056c0ebbd'


sudo: required

before_install:
  - pip3 install docker-compose

jobs:
  include:
    - stage: build
      script:
      - docker-compose up -d --build
    
    - stage: test
      script:
      - docker-compose run client yarn quasar test --unit jest
      - docker-compose run api ./test_api.sh

after_script:
  - docker-compose down --remove-orphans

after_success:
  - codecov



