language: python

python:
  - 3.6

services:
  - docker

sudo: required

before_install:
  - pip3 install docker-compose
  - chmod +x api/testes.sh

jobs:
  include:
    - stage: build
      script:
      - docker-compose up -d --build
    
    - stage: test
      script:
      - docker-compose run client yarn quasar test --unit jest
      - docker-compose run api /api/testes.sh
