language: python

python:
  - 3.6

services:
  - docker

sudo: required

env:
  - DOCKER_COMPOSE_VERSION=1.26.2

before_install:
  - pip3 install docker-compose
  
jobs:
  include:
    - stage: build
      script:
      - docker-compose up -d --build
    - stage: test
      script:
      - yarn quasar test --unit jest
      - docker-compose run api ./test_api.sh

after_script:
  - docker-compose down --remove-orphans
      
deploy:
  provider: heroku
  api_key: $HEROKU_KEY     
  app: gcesprojetofinal
  skip_cleanup: true 
