version: "3"

services:
  db:
    image: postgres:13
    env_file:
      - bd.env
    expose: 
      - "5432"

  api:
    build: ./api/
    command: bash -c "wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.1.1/wait-for | sh -s -- db:5432 -- echo Success && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    env_file:
      - bd.env
    depends_on:
      - db

  client:
    build: ./client/
    container_name: client-container
    restart: always
    volumes: 
      - ./client:/client
      - /client/node_modules
    ports: 
      - "8080:8080"
    
